repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
      - id: pytest
        name: pytest
        entry: pytest -m unit
        language: system
        pass_filenames: false
        always_run: true
